title: 'Product'
description: 'Product'
type: flex-objects

# Flex Configuration
config:
  # Administration Configuration
  admin:
    # Admin router (optional)
    router:
      path: '/product'

    # Admin menu (optional)
    menu:
      list:
        route: '/product'
        title: 'Каталог'
        icon: fa-shop
        # Authorization to collection admin
        authorize: ['admin.product.list', 'admin.super']
        # Priority -10 .. 10 (highest goes up)
        priority: 5

    # Admin template type / folder
    template: default

    # Permissions
    permissions:
      # Primary permissions
      admin.product:
        type: crudpl
        label: 'Product'

    list:
      title: name
      fields:
        name:
          link: edit
        price:
        discount:
        leftCount:
        isHit:
        isAd:
        published:

    edit:
      title:
        template: "{{ object.name ?? 'Новый товар' }}"

    preview:
      enabled: false
      route:
      #template: '/plugins/flex-objects/directory:contacts'

  # Site Configuration
  site:
    templates:
      collection:
        # Lookup for the template layout files for collections of objects
        paths:
          - 'flex/{TYPE}/collection/{LAYOUT}{EXT}'
      object:
        # Lookup for the template layout files for objects
        paths:
          - 'flex/{TYPE}/object/{LAYOUT}{EXT}'
      defaults:
        # Default template {TYPE}; overridden by filename of this blueprint if template folder exists
        type: 'product'
        # Default template {LAYOUT}; can be overridden in render calls (usually Twig in templates)
        layout: default

  # Data Configuration
  data:
    # Object class to be used, allowing custom methods for the object
    object: 'Grav\Plugin\ProductCatalog\Flex\Types\Product\ProductObject'
    # Collection class to be used, allowing custom methods for the collections
    collection: 'Grav\Plugin\ProductCatalog\Flex\Types\Product\ProductCollection'
    # Index class to be used, works as a quick database-like lookup index
    index: 'Grav\Common\Flex\Types\Generic\GenericIndex'
    storage:
      # Storage class, use single file storage (does not support images and assets)
      class: 'Grav\Framework\Flex\Storage\SimpleStorage'
      options:
        formatter:
          # File formatter class, in this case the file is stored in markdown
          class: 'Grav\Framework\File\Formatter\JsonFormatter'
        # JSON file where all the objects will be stored
        folder: user-data://product
    search:
      # Search options
      options:
        contains: 1
      # Fields to be searched
      fields:
        - name
        - description

form:
  validation: loose
  fields:
    type:
      type: select
      label: Тип Товара
      multiple: false
      data-options@: '\Grav\Plugin\ProductCatalogPlugin::getProductTypes'
    published:
      type: toggle
      label: Опубликован
      default: 1
      options:
        1: Да
        0: Нет
      validate:
        required: true
    name:
      type: text
      label: Модель Товара
      validate:
        required: true
    brand:
      type: text
      label: Название бренда
      validate:
        required: true
    slug:
      type: text
      label: Название в ссылке
      placeholder: 'teplica-mini-2-0'
      validate:
        required: true
      classes: live-slug-from-name
    article:
      type: text
      label: Артикул
      validate:
        required: true
    meta:
      type: array
      label: PLUGIN_ADMIN.METADATA
      placeholder_key: PLUGIN_ADMIN.METADATA_KEY
      placeholder_value: PLUGIN_ADMIN.METADATA_VALUE
      outerclasses: array-horizontal
    price:
      type: number
      label: Цена
      validate:
        required: true
    discount:
      type: number
      label: Скидка
      default: 25
      prepend: '%'
      validate:
        required: true
    preview:
      type: file
      label: Первью (в Карточке)
      destination: 'user/data/images'
      multiple: false
      random_name: true
      generate_params:
        md:
          forceResize: [600]
        md_blur:
          forceResize: [600]
          gaussianBlur: [3]
      accept:
        - image/*
    gallery:
      type: file
      label: Галерея
      destination: 'user/data/images'
      multiple: true
      random_name: true
      generate_params:
        md:
          format: [webp]
          resize: [700]
        md_blur:
          resize: [700]
          gaussianBlur: [3]
        sm:
          resize: [300]
      accept:
        - image/*
    props:
      type: array
      label: Параметры
      help: Параметры из конфигураций выводятся автоматически
      placeholder_key: Производитель
      placeholder_value: Беларусь
      outerclasses: array-horizontal
    variants:
      type: list
      label: Конфигурации
      outerclasses: list-vertical list-non-sortable
      fields:
        .price:
          type: number
          label: Цена
        .params:
          type: list
          label: Параметры
          outerclasses: list-vertical list-key-value
          fields:
            .param:
              type: select
              label: Тип Товара
              multiple: false
              data-options@: ['\Grav\Plugin\ProductCatalogPlugin::getProductTypeParams', '__type-param__']
            .value:
              type: text
              label: Значение
    description:
      type: markdown
      label: Описание товара
      size: large
      validate:
        required: true